modmap:
  - name: nocaps
    remap:
      CapsLock: Ctrl_L
  - name: Right Alt Super
    remap:
      RightAlt: Left
      Henkan: Right
  - name: SandS
    remap:
      Space: [Shift_L, Space]
  - name: JP Mac
    remap:
      Yen: Grave
      Hanja: Alt_L
      Hangeul: [Shift_L, Space]
