# evdev/src/sancoders.rs
modmap:
  - name: nocaps
    remap:
      CapsLock: Ctrl_L
  - name: SandS
    remap:
      Space: [Shift_L, Space]
  - name: JP
    remap:
      Henkan: [Shift_L, Space]
      KatakanaHiragana: [Shift_L, Space]
      Muhenkan: [Shift_L, Space]
  - name: JP Mac
    remap:
      Yen: Grave
      Hanja: Alt_L
      Hangeul: [Shift_L, Space]
