#!/bin/sh

riverctl background-color       0x002b36
riverctl border-color-focused   0xff0000
riverctl border-color-unfocused 0x586e75
riverctl border-color-urgent    0xffff00
riverctl border-width           2

riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change
riverctl set-repeat 50 300

# --------------------------------------------------------------

riverctl default-layout rivertile
riverctl spawn "rivertile -view-padding 4 -outer-padding 4"

riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id "*float" float

riverctl spawn dunst
riverctl spawn gentoo-pipewire-launcher
riverctl spawn yambar
riverctl spawn ~/.azotebg

# --------------------------------------------------------------

Mod=Alt
all_tags=$(((1 << 32) - 1))

riverctl map normal $Mod P spawn "rofi -show drun"
riverctl map normal $Mod Return spawn "foot -a foot-float"
riverctl map normal $Mod J focus-view next
riverctl map normal $Mod K focus-view previous
riverctl map normal $Mod I send-layout-cmd rivertile "main-count +1"
riverctl map normal $Mod D send-layout-cmd rivertile "main-count -1"
riverctl map normal $Mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $Mod L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal $Mod+Shift Return zoom
riverctl map normal $Mod Tab focus-previous-tags
riverctl map normal $Mod+Shift C close
#riverctl map normal $Mod T output-layout tile
#riverctl map normal $Mod F output-layout float
#riverctl map normal $Mod M output-layout max
#riverctl map normal $Mod Space send-layout-cmd # reset
riverctl map normal $Mod+Shift Space toggle-float
riverctl map normal $Mod E toggle-fullscreen
riverctl map normal $Mod 0 set-focused-tags $all_tags
riverctl map normal $Mod+Shift 0 set-view-tags $all_tags
riverctl map normal $Mod Comma focus-output previous
riverctl map normal $Mod Period focus-output next
riverctl map normal $Mod+Shift Comma send-to-output -current-tags previous
riverctl map normal $Mod+Shift Period send-to-output -current-tags next
for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))
  riverctl map normal $Mod $i set-focused-tags $tags
  riverctl map normal $Mod+Shift $i set-view-tags $tags
  riverctl map normal $Mod+Control $i toggle-focused-tags $tags
  riverctl map normal $Mod+Shift+Control $i toggle-view-tags $tags
done
riverctl map normal $Mod+Shift Q exit

riverctl map-pointer normal $Mod BTN_LEFT move-view
riverctl map-pointer normal $Mod BTN_RIGHT resize-view
riverctl map-pointer normal $Mod BTN_MIDDLE toggle-float

for mode in normal locked; do
  riverctl map $mode None XF86Eject spawn 'eject -T'
  riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
  riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
  riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
  riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
  riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done
